linters:
  enable-all: false
  enable:
    - gosec 
service:
  golangci-lint-version: 1.16.0 # use the fixed version to not introduce new linters unexpectedly
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"
